### PR TITLE
Added PUT to api_custom method

### PR DESCRIPTION
**Pull request by kuroi-usagi**
I added the PUT Method to the _shutdown_printer_by_API_custom method to support switching via the Philips HUE API.

### CODE REVIEW

**Comment by devildant** [comment]
Hello,
Thank you for your work,
you forgot to edit the js, the radio was not working properly, I use checkboxes, so there is a check-in the js to mimic the behavior of a radio

```
self.listOffMode = [
			{"id" : "#shutdownprinter_mode_shutdown_gcode"},
			{"id" : "#shutdownprinter_mode_shutdown_api"},
			{"id" : "#shutdownprinter_mode_shutdown_api_custom"},
		]
		self.listOffHTTPMethode = [
			{"id" : "#shutdownprinter_api_custom_GET"},
			{"id" : "#shutdownprinter_api_custom_POST"}
		]
		self.eventChangeCheckToRadio("#shutdownprinter_mode_shutdown_gcode", self.listOffMode);
		self.eventChangeCheckToRadio("#shutdownprinter_mode_shutdown_api", self.listOffMode);
		self.eventChangeCheckToRadio("#shutdownprinter_mode_shutdown_api_custom", self.listOffMode);
		
		self.eventChangeCheckToRadio("#shutdownprinter_api_custom_GET", self.listOffHTTPMethode);
		self.eventChangeCheckToRadio("#shutdownprinter_api_custom_POST", self.listOffHTTPMethode);
```

**Comment by kuroi-usagi** [comment]
I am sorry. I did this change for a friend at the weekend and could not test it myself. I hope this fixes it.

**Comment by devildant** [comment]
it looks good to me, can your friend tested on your branch? (before I merge, because I could not test)

**Comment by kuroi-usagi** [comment]
Sorry for the late response. Yes it did work on his machine.

**Comment by devildant** [comment]
OK thx your for your work, it's merge

**Pull request merged**
